name: PHP Composer and Build WordPress Plugin

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  release:
    types: [published] # Tik kai "release" yra "published"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Create Plugin ZIP
        if: github.event_name == 'release' && github.event.action == 'published'
        run: |
          PLUGIN_DIR="wp-facebook-auto-publish-build"
          mkdir $PLUGIN_DIR
          rsync -av --exclude="$PLUGIN_DIR" . $PLUGIN_DIR/
          rm -rf $PLUGIN_DIR/.git $PLUGIN_DIR/.github
          zip -r wp-facebook-auto-publish.zip $PLUGIN_DIR/

      - name: Upload Plugin ZIP to Release
        if: github.event_name == 'release' && github.event.action == 'published'
        uses: ncipollo/release-action@v1
        with:
          artifacts: wp-facebook-auto-publish.zip
          token: ${{ secrets.GITHUB_TOKEN }}
          allowUpdates: true
