name: PHP Composer and Build WordPress Plugin

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    # 1. Atsisiųskite saugyklą
    - uses: actions/checkout@v4

    # 2. Patikrinkite composer.json ir composer.lock
    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    # 3. Naudokite kešą Composer paketams
    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    # 4. Įdiekite priklausomybes
    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    # 5. PHP testai (jei naudojate testavimo scenarijus)
    # - name: Run test suite
    #   run: composer run-script test

    # 6. Sukurkite ZIP failą, jei tai yra „release“ įvykis
    - name: Create Plugin ZIP
      if: github.event_name == 'release'
      run: |
        mkdir wp-facebook-auto-publish
        cp -R * wp-facebook-auto-publish/
        rm -rf wp-facebook-auto-publish/.git wp-facebook-auto-publish/.github
        zip -r wp-facebook-auto-publish.zip wp-facebook-auto-publish/

    # 7. Įkelkite ZIP failą į „GitHub Release“
    - name: Upload Plugin ZIP to Release
      if: github.event_name == 'release'
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./wp-facebook-auto-publish.zip
        asset_name: wp-facebook-auto-publish.zip
        asset_content_type: application/zip
