name: Build and Release WordPress Plugin

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1. Atsisiųskite kodo saugyklą
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. Sukurkite ZIP failą su tinkama struktūra
    - name: Create Plugin ZIP
      run: |
        mkdir wp-facebook-auto-publish
        cp -R * wp-facebook-auto-publish/
        zip -r wp-facebook-auto-publish.zip wp-facebook-auto-publish/

    # 3. Įkelkite ZIP failą kaip „release“ turtą
    - name: Upload Plugin ZIP to Release
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./wp-facebook-auto-publish.zip
        asset_name: wp-facebook-auto-publish.zip
        asset_content_type: application/zip
